### ISSUE TITLE
HTTP HOST error

### ISSUE THREAD

**Issue by hnyaoqingping** [Fuyukai/asyncwebsockets#3]
If I visit "ws://127.0.0.1:9222/devtools/page/D39BF37BAFD9C1E4983F9BFF46BCEB28", the HOST should be "127.0.0.1:9222".
 But now the program is set to "127.0.0.1", causing me to connect to chrome's websocket debug Interface failed.

**Comment by belm0** [comment]
I can't reproduce-- websocket port appears to be honored

**Comment by smurfix** [comment]
Closing due to no feedback from reporter
