### ISSUE TITLE
next_event() and non-data messages

### ISSUE THREAD

**Issue by belm0** [Fuyukai/asyncwebsockets#8]
`next_event()` should probably ignore non-data messages (ping, etc.) by default to reduce surprises

**Comment by belm0** [comment]
How about :
  * leave `next_event()` as is
  * add `next_data_event()`, which handles ping, disconnect, and other non-data messages internally
  * change websocket iterator to use `next_data_event()`

so that it's friendly out of the box, but users can take full control with custom iteration and `next_event()`

**Comment by Fuyukai** [comment]
I don't see a reason to ignore these events. You can just do an isinstance(...) check on your code.

**Comment by belm0** [comment]
My point is that it's error prone because the other message types are relatively rare and users aren't thinking of them.  It happened in your own coded example.

I've seen other I/O libraries offer this.  Moreover, it's useful to have ping handled out of the box.

**Comment by Fuyukai** [comment]
To be fair, the example was a "written in 60s out of the shower" bit of code.
